---
kind: pipeline
type: kubernetes
name: rtp-email-lib

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:latest
  commands:
  - /root/entrypoint.sh
  - git fetch --tags
  - sbt clean test
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_USERNAME: regt-build-bot
    MONGO_HOST: database
  when:
    event:
    - push
    - tag

- name: publish
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/scala-sbt:latest
  commands:
  - /root/entrypoint.sh
  - sbt +publish
  environment:
    ARTIFACTORY_PASSWORD:
      from_secret: ARTIFACTORY_PASSWORD
    ARTIFACTORY_SERVER: https://artifactory.digital.homeoffice.gov.uk/
    ARTIFACTORY_USERNAME: regt-build-bot
  when:
    event:
    - push
    - tag
  depends_on:
    - build
services:
- name: database
  pull: if-not-exists
  image: mongo

...
